"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const packet_controller_1 = require("../controllers/packet.controller");
const router = (0, express_1.Router)();
router.post('/', packet_controller_1.postPacket);
router.get('/', packet_controller_1.getAllPackets);
router.get('/:id', packet_controller_1.getPacketById);
router.put('/:id', packet_controller_1.updatePacketById);
router.delete('/:id', packet_controller_1.deletePacketById);
exports.default = router;
